name: Deploy to surge

on: 
    push:
        branches:
            - main
        paths-ignore:
            - ".github/workflows/actions.yml"
jobs:
    Deploy-to-surge:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
