name: Deploy to surge

on: 
    push:
        branches:
            - main
        paths-ignore:
            - ".github/workflows/actions.yml"
            - ".github/workflows/checkout-with-actions.yaml"
            - ".github/workflows/checkout.yaml"
jobs:
    Deploy-to-surge:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: Deploy to surge M
              uses: dswistowski/surge-sh-action@v1
              with:
                  domain: 'mosaic-nm-test-gh.surge.sh'
                  project: './src'
                  login: ${{ secrets.SRG_NAME }}
                  token: ${{ secrets.SRG_TOKEN }}
